// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebarsPortfolioHome = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  sidebarsPortfolio: [
    'intro',
    {
      type: 'category',
      label: 'Case Studies',
      link: { type: 'doc', id: 'case-studies/index' },
      items: [
        'case-studies/integration-tools', 
        'case-studies/issue-creation-workflow-with-objects',
        'case-studies/atlassian-ecosystem-support',
        'case-studies/custom-development-automation-jira'
      ],
    },
  ],
   
};

export default sidebarsPortfolioHome;
