// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Project Performance & Flow Analytics',
      items: [
        'project-performance-and-flow-analytics/ppfa-overview',
        'project-performance-and-flow-analytics/ppfa-getting-started',
        'project-performance-and-flow-analytics/ppfa-key-indicators-period-analyzed',
        'project-performance-and-flow-analytics/ppfa-quick-cards',
        'project-performance-and-flow-analytics/ppfa-flow-health'
      ],
    },
  ],
   
};

export default sidebars;
